name: Typecode backend

on:
  push:
    branches: [develop, master]
    paths:
      - 'server/src/**'
      - '.github/**'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/typeblind/typeblind/

    - name: Debug
      run: |
        pwd
        echo ${GOPATH}
        echo ${GOROOT}

    - name: Get dependencies
      run: |
        cd $(pwd)/go/src/github.com/typeblind/typeblind/server
        go mod download -x
      env:
        GOPATH: /home/runner/work/typecode/go
    - name: Build
      run: 
        |
        cd $(pwd)/go/src/github.com/typeblind/typeblind/server
        go build -v .
      env:
        GOPATH: /home/runner/work/typecode/go

    - name: Test
      run: 
        |
        cd $(pwd)/go/src/github.com/typeblind/typeblind/server
        go test -v ./...
      env:
        GOPATH: /home/runner/work/typeblind/go